### ISSUE TITLE
Script doesn't work in Windows Linux subsytem (Ubuntu)

### ISSUE THREAD

**Issue by drewblay** [drewblay/Compare-File-To-Hash#2]
The Windows Linux subsytem won't treats the file path as PosixPath object instead of a string.

```
Traceback (most recent call last):
  File "/usr/local/bin/cfth", line 33, in <module>
    file_hash = subprocess.run([digests[hash_digest], file_to_hash], stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
```

**Comment by drewblay** [comment]
The file path is now forced to a string.
